/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.2
 * Generated at: 2025-05-26 13:59:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1744016152803L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Downloads/wetransfer_jee_2025-05-24_2041/PatientManagementApp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PatientManagementApp/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664449878000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Inscription - Patient Management System</title>\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("        <div class=\"col-md-8 col-lg-6\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <div class=\"card-header text-center\">\r\n");
      out.write("                    <h2 class=\"mb-0\"><i class=\"fas fa-user-plus me-2\"></i>Inscription</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/register\" method=\"post\" class=\"needs-validation\" novalidate>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label class=\"form-label\"><i class=\"fas fa-user me-2\"></i>Nom</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"nom\" name=\"nom\" required\r\n");
      out.write("                                       placeholder=\"Entrez votre nom\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label class=\"form-label\"><i class=\"fas fa-user me-2\"></i>Prénom</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"prenom\" name=\"prenom\" required\r\n");
      out.write("                                       placeholder=\"Entrez votre prénom\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <label class=\"form-label\"><i class=\"fas fa-envelope me-2\"></i>Email</label>\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" required\r\n");
      out.write("                                   placeholder=\"Entrez votre email\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label class=\"form-label\"><i class=\"fas fa-lock me-2\"></i>Mot de passe</label>\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"motDePasse\" name=\"motDePasse\" required\r\n");
      out.write("                                       placeholder=\"Créez un mot de passe\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-md-6 mb-4\">\r\n");
      out.write("                                <label class=\"form-label\"><i class=\"fas fa-lock me-2\"></i>Confirmer le mot de passe</label>\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"confirmerMotDePasse\" name=\"confirmerMotDePasse\" required\r\n");
      out.write("                                       placeholder=\"Confirmez le mot de passe\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"mb-4\">\r\n");
      out.write("                            <label class=\"form-label\"><i class=\"fas fa-user-tag me-2\"></i>Type de compte</label>\r\n");
      out.write("                            <select class=\"form-select\" id=\"role\" name=\"role\" required onchange=\"toggleMedecinFields()\">\r\n");
      out.write("                                <option value=\"patient\">Patient</option>\r\n");
      out.write("                                <option value=\"medecin\">Médecin</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Doctor-specific fields -->\r\n");
      out.write("                        <div id=\"medecinFields\" class=\"border rounded p-3 mb-4\" style=\"display: none;\">\r\n");
      out.write("                            <h5 class=\"mb-3\"><i class=\"fas fa-stethoscope me-2\"></i>Informations du médecin</h5>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label class=\"form-label\"><i class=\"fas fa-user-md me-2\"></i>Spécialité</label>\r\n");
      out.write("                                <select class=\"form-select\" id=\"specialite\" name=\"specialite\">\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label class=\"form-label\"><i class=\"fas fa-id-card me-2\"></i>Numéro d'ordre des médecins</label>\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"numeroOrdre\" name=\"numeroOrdre\"\r\n");
      out.write("                                       placeholder=\"Entrez votre numéro d'ordre\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-4\">\r\n");
      out.write("                                <label class=\"form-label\"><i class=\"fas fa-clock me-2\"></i>Années d'expérience</label>\r\n");
      out.write("                                <input type=\"number\" class=\"form-control\" id=\"anneesExperience\" name=\"anneesExperience\" min=\"0\"\r\n");
      out.write("                                       placeholder=\"Nombre d'années d'expérience\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-grid gap-2\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary btn-lg\">\r\n");
      out.write("                                <i class=\"fas fa-user-plus me-2\"></i>S'inscrire\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"text-center mt-4\">\r\n");
      out.write("                            <p class=\"mb-0\">Déjà inscrit? \r\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"text-decoration-none\">\r\n");
      out.write("                                    <i class=\"fas fa-sign-in-alt me-1\"></i>Se connecter\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS and Popper.js -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function toggleMedecinFields() {\r\n");
      out.write("    var role = document.getElementById('role').value;\r\n");
      out.write("    var medecinFields = document.getElementById('medecinFields');\r\n");
      out.write("    var specialite = document.getElementById('specialite');\r\n");
      out.write("    var numeroOrdre = document.getElementById('numeroOrdre');\r\n");
      out.write("    var anneesExperience = document.getElementById('anneesExperience');\r\n");
      out.write("    \r\n");
      out.write("    if (role === 'medecin') {\r\n");
      out.write("        medecinFields.style.display = 'block';\r\n");
      out.write("        specialite.required = true;\r\n");
      out.write("        numeroOrdre.required = true;\r\n");
      out.write("        anneesExperience.required = true;\r\n");
      out.write("    } else {\r\n");
      out.write("        medecinFields.style.display = 'none';\r\n");
      out.write("        specialite.required = false;\r\n");
      out.write("        numeroOrdre.required = false;\r\n");
      out.write("        anneesExperience.required = false;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// Form validation\r\n");
      out.write("document.querySelector('form').addEventListener('submit', function(e) {\r\n");
      out.write("    var motDePasse = document.getElementById('motDePasse').value;\r\n");
      out.write("    var confirmerMotDePasse = document.getElementById('confirmerMotDePasse').value;\r\n");
      out.write("\r\n");
      out.write("    if (motDePasse !== confirmerMotDePasse) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        alert('Les mots de passe ne correspondent pas!');\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// Initialize fields visibility on page load\r\n");
      out.write("document.addEventListener('DOMContentLoaded', toggleMedecinFields);\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /views/register.jsp(75,36) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/register.jsp(75,36) '${specialites}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${specialites}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /views/register.jsp(75,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("specialite");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${specialite.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${specialite.nom}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
